-- Migración: Documentación de campos de fecha/hora en deadtimes
-- Fecha: 2025-12-02
-- 
-- NOTA: Los campos de fecha ya existen en la tabla deadtimes:
--   - hr: Hora de Registro (fecha/hora de creación del ticket)
--   - ha: Hora de Atención (fecha/hora de inicio de atención por el técnico)
--   - hc: Hora de Cierre (fecha/hora de cierre/finalización del ticket)
--
-- Estos campos ya están implementados, esta migración es solo documentación.
--
-- REGLAS DE NEGOCIO IMPLEMENTADAS:
-- 1) Solo usuarios con rol 'Administrador', 'Ingeniero' o 'Lider' pueden crear/abrir tickets
-- 2) Solo usuarios con rol 'Tecnico' o 'Soporte' pueden ser asignados para atender tickets
-- 3) Se muestran las 3 fechas en el detalle del ticket:
--    - Fecha/Hora de Creación (hr)
--    - Fecha/Hora de Inicio de Atención (ha)
--    - Fecha/Hora de Cierre (hc)
--
-- La tabla 'users' en credenciales ya tiene el enum actualizado:
-- ALTER TABLE users 
-- MODIFY COLUMN rol ENUM(
--   'The Goat','AOI','Mantenimiento','Supervisor','Modula','Tecnico',
--   'Ingeniero','Administrador','Magazines','Calidad','Soporte',
--   'Lider','Operador','Invitado','Recursos Humanos','Tool Room'
-- ) NOT NULL;

-- Verificar estructura actual de la tabla deadtimes
DESCRIBE deadtimes;

-- Los campos hr, ha, hc deberían aparecer como:
-- hr  | datetime | YES | | NULL | 
-- ha  | datetime | YES | | NULL |
-- hc  | datetime | YES | | NULL |
